# Generated by Django 6.0.6 on 2026-07-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticket_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]

#For AI check: this is auto generated code by django so don't pay attention to single quotes
